### ISSUE TITLE
ION API Sample not working

### ISSUE THREAD

**Issue by Jags1104** [infor-cloud/widget-sdk#10]
Hi ,

Please find the below attached error when trying to run the ION API sample

![Widget ION API Error](https://user-images.githubusercontent.com/80663210/113576716-b5129f00-963d-11eb-89a0-4f8fa55dc381.JPG)

I have followed all the steps mentioned in the document, Also when I try to access the URL in browser I get unauthorized error
![image](https://user-images.githubusercontent.com/80663210/113576949-176b9f80-963e-11eb-9891-ae4a96be8c1d.png)

**Comment by volante007** [comment]
Hi,

It seems to me that you don't have a proxy running. The ION API samples run fine for me, so make sure that everything is set up properly.

# Proxy needs to be running against proper host and port of ION API server of the environment you're targeting
# OAuth token needs to be retrieved and put in `configuration.json` 
# Tenant name must be correct in `configuration.json`
# devConfiguration must be set on the widget in index.html 

For more details, see the Dev. Guide, there's also info in the `.ts` files of the ION API samples (Social / M3).
