### ISSUE TITLE
Drillback LN via widget

### ISSUE THREAD

**Issue by alerappini2ws** [infor-cloud/widget-sdk#19]
Hello Infor,

I'm working with widget, I need to drillback a LN session via a button.
Is it possible?
Is possible to have a sample or some documentation to do that?

BR

Alessandro

**Comment by karinpb** [comment]
If you need to go from a widget to LN there are two options, drillback or favorite context. Then both look like the query part of an URL and should be launched with the IWidgetContext.launch() method in the widget.

The drillback has a logicalId parameter with the value of the LN logicalId instance. For a provisioned application this id would usually be the same for all tenants, but it can depend on region. I'm not sure what the default logicalId is for LN. But if you are writing your own widget, and you have added an application dependency in the manifest to LN, then you can get the application information through the Widget Context. 

The favoriteContext is what you see as part of the URL in the addressbar in the browser. It's the part that starts with ?favoriteContext. You can see that it changes as you navigate around in Mingle. That subpart can also be used with the launch method. But you should always get the current logicalId from the application object in the widget.

This is a sample from one of the standard LN widgets. Notice that some of the variables are member variables altough they don't need to be. First you get the application for the widget (check documentation on the widget manifest to add application dependency). This code also shows a widget message if the drillback inforamtion cannot be successfully retrieved.
As for which parameters to use depending on the program/view etc, I don't know. I recommend checking the LN documenation, contacting Infor Support, or using the Infor Communities to ask a question (https://community.infor.com/)

`	drillback(): void {
		const application: IApplication = this.widgetContext.getApplication();
		if (application) {
			this.logicalId = application.logicalId + "/" + this.company;
		}
		const logPrefix = "[" + this.widgetContext.getStandardWidgetId() + "]";
		if (!StringUtil.isNullOrWhitespace(this.logicalId)) {
			this.widgetContext.removeWidgetMessage();

			const drillbackUrl = "?LogicalId=" + this.logicalId +
				"&WarehouseID=" + encodeURIComponent(this.warehouseId) +
				"&SiteID=" + encodeURIComponent(this.siteId) +
				"&ItemID=" + encodeURIComponent(this.selectedItem.itemId) +
				"&ViewId=Inventory_WT_Expected_Inventory_Transactions";

			Log.debug(logPrefix + "Drillback message sent to " + drillbackUrl);
			this.widgetContext.launch({ url: drillbackUrl });
		} else {
			Log.warning(logPrefix + " Invalid drillback URL with logical ID " + this.logicalId);
			this.widgetContext.showWidgetMessage({
				type: WidgetMessageType.Alert,
				message: this.lang.get("cannotDrillback"),
			});
		}
	}`
