### ISSUE TITLE
Trying to Fetch an Infor ION API data in Custom Widget

### ISSUE THREAD

**Issue by Vinaymohite** [infor-cloud/widget-sdk#21]
Hi Infor,
As per your sample HelloWorld Widget, we tried and got success but we need to know how we can fetch Infor ION API in the custom Widget using JQUERY.
Is there any Documents like the Development Guide or else can you share the sample widget which is fetching the data from Infor ION API
Please Help us out

**Comment by anhallbe** [comment]
Hi!
There are two sample widgets that show how to use `IWidgetContext.executeIonApiAsync()`:
- infor.sample.ionapi.social
- infor.sample.ionapi.m3

These are both Angular widgets, but the method for doing ION API requests is not Angular-specific. This should also be documented in the Developers Guide.
