### ISSUE TITLE
How to show H5 app within widget

### ISSUE THREAD

**Issue by naveenkumarpvince** [infor-cloud/widget-sdk#32]
How to show H5 app within widget?

**Comment by anhallbe** [comment]
H5 apps (built with the h5-sdk/Odin) are really meant to run as iframes inside H5, served from the same Origin.

While technically a H5 app is just a static website/SPA that can be served from anywhere, it won't be able to do much if it can't communicate with H5.

**Comment by naveenkumarpvince** [comment]
So if my H5 app path is /mne/app/testapp, 
How to bind with iframe?

Thanks
