### ISSUE TITLE
Widget SDK version for Infor LTR

### ISSUE THREAD

**Issue by NelsonCBG** [infor-cloud/widget-sdk#33]
Hi team, we're planning to upgrade our Infor OS on premises, currently on version 2022.06.01 to the new Infor LTR. Our Widget SDK is 3.14. Which would be the correspondent SDK after the upgrade?

Thanks,
Nelson Castelo Branco

**Comment by gustavpollak** [comment]
Hi Nelson!
I'm unsure of which version of the SDK Infor LTR is running, but after upgrade you could check the version and download the corresponding Widget SDK version from the Releases section.
