### ISSUE TITLE
Lime update to match @infor-lime/core from cloud version?

### ISSUE THREAD

**Issue by davekersten** [infor-cloud/widget-sdk#37]
I'm trying to use the SDK to edit standard Infor widgets and keep running into methods that aren't available in lime, but are available in the live cloud version (@infor-lime/core).  Is the lime version in SDK just out of date, or is there functionality left out on purpose?  Is there a way to update the lime version in the SDK?

Example:  In the infor.sxe.buyer.onyourradar.productivity widget, they call .getPortal() in the IWidgetContext class.  But it doesn't exist in lime, only in @infor-lime/core.  Same with setSubTitle().

**Comment by karinpb** [comment]
It’s intentionally not included since that is for OS Portal and this SDK is for Mingle Homepages.
