### ISSUE TITLE
Purpose built API development

### ISSUE THREAD

**Issue by WP-Ben** [infor-cloud/widget-sdk#8]
Hi,
In the developers guide of the homepages widget sdk it is recommended to use 'Purpose built APIs for charts as client side calculations on data sets does not deliver high performance'. I fully understand the reason for this. 
My question: where can I find more information on developing purpose built API's? Is there a developers guide like this one for the widget sdk?
Greetings,
Ben

**Comment by karinpb** [comment]
There is no generic developers guide for this. It depends on the cababilities for the Could Suite that you would like to connect to.
